<?php

namespace DevisBundle\Repository;

/**
 * BonCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonCommandeRepository extends \Doctrine\ORM\EntityRepository
{
}
