<?php

namespace DevisBundle\Repository;

/**
 * ComposantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComposantRepository extends \Doctrine\ORM\EntityRepository
{
}
