<?php

namespace DevisBundle\Repository;

/**
 * GammeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GammeRepository extends \Doctrine\ORM\EntityRepository
{
}
