<?php

namespace DevisBundle\Repository;
use DevisBundle\Entity\Gamme;

/**
 * GammeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GammeRepository extends \Doctrine\ORM\EntityRepository
{
    public function GetGamme($idModele){
        return $this->createQueryBuilder('m')
        ->where("m.fk_modele = :idModele")
        ->setParameter('idModele', $idModele)
        ->getQuery()
        ->getResult();
    }
}
