<?php

namespace DevisBundle\Repository;

/**
 * ModeleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeleRepository extends \Doctrine\ORM\EntityRepository
{
}
