<?php

namespace DevisBundle\Repository;

/**
 * MoyenPaiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoyenPaiementRepository extends \Doctrine\ORM\EntityRepository
{
}
