<?php

namespace DevisBundle\Repository;

/**
 * TeinteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeinteRepository extends \Doctrine\ORM\EntityRepository
{
}
