<?php

namespace DevisBundle\Repository;

/**
 * TypeEtatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeEtatRepository extends \Doctrine\ORM\EntityRepository
{
}
