<?php

namespace DevisBundle\Repository;

/**
 * UsrTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsrTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
